spring:
  application:
    name: micro-eureka-server
info:
  app:
     name: ${spring.application.name}
     version: v1.0.0
logging:
  config: classpath:log4j2.xml
server:
  port: 8030
  context-path: /
  tomcat:
    uri-encoding: UTF-8    
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/